# Generated by Django 5.2.3 on 2025-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekknuser',
            name='invited_by',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
