# Generated by Django 5.2.3 on 2025-10-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0002_alter_trekknuser_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekknuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='conversion_rate',
            field=models.FloatField(default=0.05),
        ),
    ]
