# Generated by Django 5.2.3 on 2025-10-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0002_alter_trekknuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trekknuser',
            managers=[
            ],
        ),
    ]
