# Generated by Django 5.2.3 on 2025-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0003_alter_trekknuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekknuser',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
