# Generated by Django 5.2.3 on 2025-10-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0004_alter_trekknuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekknuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trekknuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
