# Generated by Django 5.2.3 on 2025-10-02 19:53

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0005_alter_trekknuser_device_id_alter_trekknuser_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trekknuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
