# Generated by Django 5.2.3 on 2025-10-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0006_alter_trekknuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trekknuser',
            name='name',
        ),
        migrations.AddField(
            model_name='trekknuser',
            name='displayname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='trekknuser',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
