# Generated by Django 5.2.3 on 2025-10-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0007_remove_trekknuser_name_trekknuser_displayname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trekknuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
