# Generated by Django 5.2.3 on 2025-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('trekkn', '0008_alter_trekknuser_device_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trekknuser',
            options={},
        ),
        migrations.AlterField(
            model_name='trekknuser',
            name='device_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='trekknuser',
            constraint=models.UniqueConstraint(fields=('device_id',), name='unique_device_id'),
        ),
    ]
