# Generated by Django 5.2.3 on 2025-10-03 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0009_alter_trekknuser_options_alter_trekknuser_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL),
        ),
    ]
