# Generated by Django 5.2.3 on 2025-10-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trekkn', '0011_alter_dailyactivity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekknuser',
            name='evm_addr',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trekknuser',
            name='evm_key',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trekknuser',
            name='sol_addr',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trekknuser',
            name='sol_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
